---
- hosts: all
  remote_user: root
  become: yes
  tasks:

    - name: ask for verification
      pause:
        prompt: "Are you sure you want to reboot specified hosts? Clt-c to cancel else press any key to continue"

    - name: "reboot hosts"
      reboot:
        msg: "Reboot triggered by Ansible"
        reboot_timeout: 360
