apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp1-replicaset1
  labels:
    app: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp1
    spec:
      containers:
        - name: nginx
          image: nginx
      

