---
- hosts: all
  remote_user: root
  become: true
  vars:
    service_name: "{ kdump.service }"
  
  tasks:
      - name: ensure service state running ---
        service:
             name: "{ service_name }"
             state: started
