---
- hosts: all
  remote_user: root
  become: true
  gather_facts: no
  tasks:
      - name: ensure service state running
        service:
             name: "{ service_name }"
             state: started
        register: Active
