---
- hosts: all
  gather_facts: no
  display_skipped_hosts = false
  vars_prompt:
     - name: pkg_name
       prompt: enter package name
       default: apache
       private: no
       
  tasks:
          
      - name: Download the Apache installer
        win_get_url:
          url:  'https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi'
          dest: 'C:\temp\httpd-2.2.25-win32-x86-no_ssl.msi'
        when: pkg_name  == "apache"

      - name: Install Apache MSI
        win_package:
          path: 'C:\temp\httpd-2.2.25-win32-x86-no_ssl.msi'
          state: present
        when: pkg_name == "apache"

      - name: Download the 7z installer
        win_get_url:
          url:  'https://www.7-zip.org/a/7z1701-x64.msi'
          dest: 'C:\temp\7z.msi'
        when: pkg_name == "7z"

      - name: Install 7z MSI
        win_package:
          path: 'C:\C:\temp\7z.msi'
          state: present
        when: pkg_name == "7z"